export const STAFF_LIST = [
  "ROBY FERNANDEZ, SH. MM",
  "AJI MASPUTRA, S.H.",
  "PANCAWATI, S.H.",
  "ETI FITRIANI, S.AP",
  "ELIYA SYAM, S.H.",
  "SYARIFUDDIN, S.Sos.",
  "TARMIZI,S.H.",
  "MUHAMMAD LUBIS, S.H.",
  "HENNY WAHYUNI, S.P.",
  "I WAYAN WIDHIASTA, S.H.",
  "M. ARIEF SAHLANI, S.Psi.",
  "BENG PRAMONO, S.Sos.",
  "MUHAMMAD IQBAL, S.H.",
  "ALBERTUS BAYU PRAKOSO, S.Sos.",
  "ADIE SETIAWAN",
  "RIZKI SETIAJI MUTAQIN, S.Sos.",
  "NURFAUZIAH AMALIA MUBARAK, S.Tr.Pas.",
  "FIKRI IFTIKAR HUMAM MUHYIDDIN, S.Tr.Pas.",
  "SYAMSUL ARIFIN",
  "SUARDI NINGGRAT",
  "AGUS MULYONO",
  "IMAM HARMAEN",
  "SEPTIAN WAHYU PRATAMA",
  "AGUNG TRI SAKTI, S.Tr.Pas.",
  "TUBAGUS HAEKAL ER GHIFARI, S.Tr.Pas."
];

export const HEAD_OF_OFFICE = {
  name: "ROBY FERNANDEZ, S.H., M.M.",
  nip: "198608062007031003"
};
